### ISSUE TITLE
score_*.csv のカラムの意味

### ISSUE THREAD

**Issue by harumichi** [tmu-nlp/JapaneseWordSimilarityDataset#3]
score_adj.csv のカラム mean, sub_1, ..., sub_10 について

mean = (sub_1 + ... + sub_10) / 10 という定義でしょうか。

score_adj.csvの２行目を見ると
"あっけなく,苦労なく,4.8,3,6,5,3,7,8,7,6,8,9" 
(sub_1 + ... + sub_10) / 10 = (3 + 6 + 5 + 3 + 7 + 8 + 7 + 6 + 8 + 9) / 10 = 6.2
これが4.8 と異なるのは上記の理解が間違っているのでしょうか。

**Comment by yuya-sakaizawa** [comment]
@harumichi 

ご指摘ありがとうございます。  
`mean` の列が平均である認識は間違っていません。
READMEに記載するべき内容でしたが、今アップしているデータの mean 列はアノテータの信頼度を計算して `信頼出来ないアノテータは除いた上での平均` を計算しています。  
これにより、極端なアノテーションを付けがちな人の結果を除いてより確からしい平均を計算しているつもりです。  
なので上記例で言うとどこかの列のアノテータの結果が取り除かれた上で 4.8 という数字が計算されています。
説明が不足していて申し訳ありません。

この後、以下の2つの対応を行いたいと考えています。

1. READMEに上記旨を記載
2. 単純に平均を出した列を追加

READMEに記載がなく、混乱を招いてしまい申し訳ありませんでした。

**Comment by harumichi** [comment]
承知しました。ありがとうございます。
